[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tangram_history"
version = "0.2.0"
license = "AGPL-3.0"
readme = "readme.md"
dependencies = ["tangram_core", "platformdirs"]
authors = [
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]

[project.entry-points."tangram_core.plugins"]
tangram_history = "tangram_history:plugin"

[tool.uv.sources]
tangram_core = { workspace = true }

[tool.maturin]
python-source = "src"
module-name = "tangram_history._history"
features = ["pyo3", "server"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "rust/Cargo.toml" },
    { file = "**/*.rs" },
]
