[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tangram_history"
version = "0.1.0"
dependencies = ["tangram>=0.2.0", "platformdirs"]
authors = [
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]

[project.entry-points."tangram.plugins"]
tangram_history = "tangram_history:plugin"

[tool.uv.sources]
tangram = { workspace = true }

[tool.maturin]
python-source = "src"
module-name = "tangram_history._history"
features = ["pyo3"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "rust/Cargo.toml" },
    { file = "**/*.rs" },
]