[core]
redis_url = "redis://localhost:6379"
plugins = [
    # "tangram_example",
    "tangram_system",
    "tangram_airports",
    "tangram_jet1090",
    "tangram_ship162",
    "tangram_history",
    # "tangram_weather"
]

[server]
host = "0.0.0.0"
port = 2346

[channel]
host = "0.0.0.0"
port = 2347
jwt_secret = "a-better-secret-than-this"
jwt_expiration_secs = 315360000

[plugins.tangram_jet1090]
jet1090_channel = "jet1090"
state_vector_expire = 20