[project]
name = "tangram-explore"
version = "0.3.0"
description = "Tangram plugin for exploring any Arrow-backed dataframe"
readme = "readme.md"
requires-python = ">=3.10"
# pyarrow is the gold standard for parquet serialisation but its very huge, keeping it minimal
# we accept any object that adheres to the arrow C interface and thus do not require polars/pandas
dependencies = ["tangram_core>=0.2.1", "arro3-core>=0.4.0", "arro3-io>=0.4.0"]

[project.entry-points."tangram_core.plugins"]
tangram_explore = "tangram_explore:plugin"

[project.optional-dependencies]
polars = ["polars>=1"]

[tool.uv.sources]
tangram_core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
