[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tangram_weather"
version = "0.2.1"
description = "Weather data integration plugin for tangram"
readme = "readme.md"
requires-python = ">=3.10"
license = "AGPL-3.0"
authors = [
    { name = "Xavier Olive", email = "git@xoolive.org" }
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Atmospheric Science",
    "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = [
    "tangram_core>=0.2.0",
    "xarray>=2025.6.1",
    "cfgrib>=0.9.15.0",
    "tqdm>=4.67.1",
    "orjson>=3.10.18",
    "pandas",
    "numpy>=2",
    "pillow>=10",
]

[project.entry-points."tangram_core.plugins"]
tangram_weather = "tangram_weather:plugin"

[tool.uv.sources]
tangram_core = { workspace = true }

[tool.hatch.build.targets.sdist]
ignore-vcs = true
include = ["dist-frontend/*", "src/*", "package.json"]

[tool.hatch.build.targets.wheel.force-include]
"dist-frontend" = "tangram_weather/dist-frontend"
"package.json" = "tangram_weather/package.json"
