[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tangram_example"
version = "0.2.1"
readme = "readme.md"
dependencies = ["tangram_core>=0.2.0"]
classifiers = ["Private :: Do Not Upload"]
authors = [
    { name = "Xavier Olive", email = "git@xoolive.org" },
    { name = "Junzi Sun", email = "git@junzis.com" },
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]

[project.entry-points."tangram_core.plugins"]
tangram_example = "tangram_example:plugin"

[tool.hatch.build.targets.sdist]
ignore-vcs = true
include = ["dist-frontend/*", "src/*"]

[tool.hatch.build.targets.wheel.force-include]
"dist-frontend" = "tangram_example/dist-frontend"
"package.json" = "tangram_example/package.json"  # including `package.json` is not required, but allows `uvx tangram check-plugin` to work properly

[tool.uv.sources]
tangram_core = { workspace = true }
