[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tangram_core"
version = "0.2.0"
description = "A framework for real-time analysis of ADS-B and Mode S surveillance data"
authors = [
    { name = "Xavier Olive", email = "git@xoolive.org" },
    { name = "Junzi Sun", email = "git@junzis.com" },
    { name = "Xiaogang Huang", email = "maple.hl@gmail.com" },
    { name = "Michel Khalaf", email = "khalafmichel98@gmail.com" },
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]
license = "AGPL-3.0"
readme = "readme.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.4",
    "uvicorn>=0.32.0",
    "redis>=5.2.0",
    "httpx[http2]>=0.27.2",
    "pydantic>=2.6.1",
    "typer",                          # provides rich
    "tomli; python_version < '3.11'",
    "platformdirs>=4.5.0",
]

[project.scripts]
tangram = "tangram_core.__main__:app"

[tool.maturin]
python-source = "src"              # needed for stubgen to output path correctly.
module-name = "tangram_core._core"
features = ["pyo3", "channel"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "rust/Cargo.toml" },
    { file = "**/*.rs" },
]
