[package]
name = "tangram_jet1090"
description = "tangram plugin to track aircraft using jet1090"
readme = "../readme.md"
authors = ["Abraham Cheung <abraham@ylcheung.com>"]
version.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
homepage.workspace = true

[lib]
name = "_planes"
crate-type = ["cdylib", "rlib"]

[dependencies]
tangram_core_rs = { path = "../../tangram_core/rust" }
tangram_history = { path = "../../tangram_history/rust", default-features = false, features = [
    "client",
] }
arrow-array = "57.2.0"
arrow-schema = "57.3.0"

anyhow = "1.0"
futures = "0.3"
redis = { version = "1.0.2", features = ["tokio-comp"] }
rs1090 = { git = "https://github.com/xoolive/jet1090.git", rev = "7258d2e2cdbee1de5173ea0e1d31b91c24a5be7d" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nucleo-matcher = "0.3.1"

pyo3 = { version = "0.27", features = ["extension-module"], optional = true }
pyo3-async-runtimes = { version = "0.27", features = [
    "attributes",
    "tokio-runtime",
], optional = true }
# NOTE: v0.17 introduced support for overloading but that caused an odd post-compile
# runtime issue, do not upgrade yet.
pyo3-stub-gen = { version = "0.16", optional = true }

[[bin]]
name = "stub_gen_planes"
path = "src/bin/stub_gen.rs"
required-features = ["stubgen"]

[features]
pyo3 = ["dep:pyo3", "dep:pyo3-async-runtimes", "tangram_history/pyo3"]
stubgen = ["pyo3", "dep:pyo3-stub-gen"]
