[package]
name = "jet1090_planes"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Tangram jet1090 plugin"
repository = "https://github.com/open-aviation/tangram"

[lib]
name = "_planes"
crate-type = ["cdylib", "rlib"]

[dependencies]
tangram_core = { path = "../../tangram/rust" }
anyhow = "1.0"
futures = "0.3"
redis = { version = "0.29", features = ["tokio-comp"] }
rs1090 = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

pyo3 = { version = "0.27", features = ["extension-module"], optional = true }
pyo3-async-runtimes = { version = "0.27", features = [
    "attributes",
    "tokio-runtime",
], optional = true }
pyo3-stub-gen = { version = "0.17", optional = true }

[[bin]]
name = "stub_gen_planes"
path = "src/bin/stub_gen.rs"

[features]
pyo3 = ["dep:pyo3", "dep:pyo3-async-runtimes", "dep:pyo3-stub-gen"]