[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tangram_ship162"
version = "0.2.0"
dependencies = ["tangram_core"]
authors = [
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]
license = "AGPL-3.0"

[project.optional-dependencies]
history = ["polars[deltalake]"]

[project.entry-points."tangram_core.plugins"]
tangram_ship162 = "tangram_ship162:plugin"

[tool.uv.sources]
tangram_core = { workspace = true }

[tool.maturin]
python-source = "src"
module-name = "tangram_ship162._ships"
features = ["pyo3"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "rust/Cargo.toml" },
    { file = "**/*.rs" },
]
