[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tangram_system"
version = "0.2.1"
description = "System monitoring plugin for tangram"
readme = "readme.md"
requires-python = ">=3.10"
license = "AGPL-3.0"
authors = [
    { name = "Xavier Olive", email = "git@xoolive.org" },
    { name = "Junzi Sun", email = "git@junzis.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: System :: Monitoring",
]
dependencies = ["tangram_core>=0.2.0", "psutil"]

[project.entry-points."tangram_core.plugins"]
tangram_system = "tangram_system:plugin"

[tool.uv.sources]
tangram_core = { workspace = true }

[tool.hatch.build.targets.sdist]
ignore-vcs = true
include = ["dist-frontend/*", "src/*", "package.json"]

[tool.hatch.build.targets.wheel.force-include]
"dist-frontend" = "tangram_system/dist-frontend"
"package.json" = "tangram_system/package.json"
