[package]
name = "channel"
version = "0.2.7"
edition = "2021"
license = "MIT"
description = "Websocket channels compatible with Phixnix"
repository = "https://github.com/emctoo/channels"
keywords = ["axum", "axum-ws", "warp", "websocket", "channels"]

# https://doc.rust-lang.org/cargo/reference/cargo-targets.html#configuring-a-target
autobins = false

[[bin]]
name = "channel"
path = "src/bin/axum-server.rs"

# diabled for now, it does not work
# [[bin]]
# name = "channel-warp"
# path = "src/bin/warp-server.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = { version = "0.26" }
tokio-stream = "0.1"

tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["fs", "trace"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

futures = "0.3"
# futures-util = { version = "0.3.30"}

axum = { version = "0.8", features = ["default", "ws"] }
axum-extra = { version = "0.10" }

warp = { version = "0.3", features = ["default"] }

serde = "1.0"
serde_tuple = "1.1"
serde_json = "1.0"

# uuid = { version = "1.8.0", features = ["v4"] }
nanoid = { version = "0.4" }

chrono = "*"

# hex = "0.4.3"
redis = { version = "0.29", features = ["tokio-comp"] }

clap = { version = "4.5", features = ["color", "derive", "wrap_help", "env"] }
dotenv = { version = "0.15" }
jsonwebtoken = { version = "9.3" }
rand = { version = "0.9" }
itertools = "0.14"
