[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tangram_jet1090"
version = "0.2.0"
license = "AGPL-3.0"
dependencies = ["tangram_core", "platformdirs"]
authors = [
    { name = "Xavier Olive", email = "git@xoolive.org" },
    { name = "Junzi Sun", email = "git@junzis.com" },
    { name = "Xiaogang Huang", email = "maple.hl@gmail.com" },
    { name = "Michel Khalaf", email = "khalafmichel98@gmail.com" },
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]

[project.optional-dependencies]
history = ["polars[deltalake]"]

[tool.uv.sources]
tangram_core = { workspace = true }

[project.entry-points."tangram_core.plugins"]
tangram_jet1090 = "tangram_jet1090:plugin"

[tool.maturin]
python-source = "src"
module-name = "tangram_jet1090._planes"
features = ["pyo3"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "rust/Cargo.toml" },
    { file = "**/*.rs" },
]
