[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "tangram_jet1090"
version = "0.2.1"
description = "Mode S and ADS-B data integration plugin for tangram"
license = "AGPL-3.0"
readme = "readme.md"
requires-python = ">=3.10"
authors = [
    { name = "Xavier Olive", email = "git@xoolive.org" },
    { name = "Junzi Sun", email = "git@junzis.com" },
    { name = "Xiaogang Huang", email = "maple.hl@gmail.com" },
    { name = "Michel Khalaf", email = "khalafmichel98@gmail.com" },
    { name = "Abraham Cheung", email = "abraham@ylcheung.com" },
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering :: Visualization",
]
dependencies = ["tangram_core>=0.2.1"]

[project.optional-dependencies]
history = ["polars[deltalake]"]

[tool.uv.sources]
tangram_core = { workspace = true }

[project.entry-points."tangram_core.plugins"]
tangram_jet1090 = "tangram_jet1090:plugin"

[tool.maturin]
python-source = "src"
module-name = "tangram_jet1090._planes"
features = ["pyo3"]
include = ["./dist-frontend", "package.json"]

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "rust/Cargo.toml" },
    { file = "**/*.rs" },
]
